module.exports = {
  LOAD_WALLETS: 'LOAD_WALLETS',
  CHANGE_WALLET: 'CHANGE_WALLET',
  UPDATE_EXCHANGE_RATES: 'UPDATE_EXCHANGE_RATES',
  CHANGE_FROM_WALLET_INDEX: 'CHANGE_FROM_WALLET_INDEX',
  CHANGE_TO_WALLET_INDEX: 'CHANGE_TO_WALLET_INDEX',
  ENTER_AMOUT_FOR_EXCHANGE: 'ENTER_AMOUT_FOR_EXCHANGE',
  ADD_EXCHANGE_TRANSACTION: 'ADD_EXCHANGE_TRANSACTION'
}
